"use client"

import { useCallback, useEffect, useState } from "react"
import { Archive, CalendarDays, Loader2, Pencil, Plus, Search } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { AdminImageUpload } from "@/components/admin/image-upload"
import { TranslationTabs } from "@/components/admin/translation-tabs"
import type { Locale } from "@/lib/i18n"

type EventRecord = { id: string; title: string; slug: string; description: string; image: string | null; startDate: string; endDate: string | null; startTime: string | null; endTime: string | null; venue: string | null; location: string | null; organizer: string | null; registrationLink: string | null; contact: string | null; category: string | null; status: string; translations: string }
const EMPTY = { title: "", slug: "", description: "", image: "", startDate: "", endDate: "", startTime: "", endTime: "", venue: "", location: "", organizer: "", registrationLink: "", contact: "", category: "", status: "DRAFT", translations: "{}" }
const slugify = (value: string) => value.normalize("NFKD").toLowerCase().replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")
const inputDate = (value: string | null) => value ? value.slice(0, 10) : ""

export function EventsManager() {
  const [events, setEvents] = useState<EventRecord[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState("")
  const [editing, setEditing] = useState<EventRecord | null>(null); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [form, setForm] = useState<Record<string, string>>(EMPTY)
  const [translations, setTranslations] = useState<Record<string, any>>({}); const [locale, setLocale] = useState<Locale>("en")
  const load = useCallback(async () => { setLoading(true); try { const res = await fetch("/api/admin/events"); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Could not load events."); setEvents(data.events || []) } catch (error) { toast.error(error instanceof Error ? error.message : "Could not load events.") } finally { setLoading(false) } }, [])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  function change(key: string, value: string) { setForm((current) => ({ ...current, [key]: value, ...(key === "title" && !editing ? { slug: slugify(value) } : {}) })) }
  function add() { setEditing(null); setTranslations({}); setLocale("en"); setForm({ ...EMPTY }); setOpen(true) }
  function edit(event: EventRecord) { setEditing(event); try { setTranslations(JSON.parse(event.translations || "{}")) } catch { setTranslations({}) }; setLocale("en"); setForm({ ...event, image: event.image || "", startDate: inputDate(event.startDate), endDate: inputDate(event.endDate), startTime: event.startTime || "", endTime: event.endTime || "", venue: event.venue || "", location: event.location || "", organizer: event.organizer || "", registrationLink: event.registrationLink || "", contact: event.contact || "", category: event.category || "" }); setOpen(true) }
  async function save() {
    if (!form.title.trim() || !form.slug.trim() || !form.startDate) { toast.error("Enter the event title, URL slug, and start date."); return }
    setSaving(true)
    try { const res = await fetch(editing ? `/api/admin/events/${editing.id}` : "/api/admin/events", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, translations: JSON.stringify(translations), endDate: form.endDate || null }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "The event could not be saved."); toast.success(editing ? "Event updated." : "Event created."); setOpen(false); await load() } catch (error) { toast.error(error instanceof Error ? error.message : "The event could not be saved.") } finally { setSaving(false) }
  }
  async function archive(event: EventRecord) { if (!window.confirm(`Archive “${event.title}”? It will be removed from the public events page.`)) return; const res = await fetch(`/api/admin/events/${event.id}`, { method: "DELETE" }); const data = await res.json().catch(() => ({})); if (!res.ok) { toast.error(data.error || "Could not archive event."); return }; toast.success("Event archived."); await load() }
  const visible = events.filter((event) => `${event.title} ${event.location || ""} ${event.category || ""}`.toLowerCase().includes(query.toLowerCase()))
  const field = (label: string, key: string, type = "text", placeholder = "") => <div className="space-y-1.5" key={key}><Label htmlFor={`event-${key}`}>{label}</Label><Input id={`event-${key}`} type={type} value={form[key] || ""} placeholder={placeholder} disabled={key === "slug" && !!editing} onChange={(event) => change(key, event.target.value)} /></div>
  const localizedInput = (label: string, key: string) => <div className="space-y-1.5" key={key}><Label>{label}</Label><Input value={locale === "en" ? form[key] || "" : translations?.[locale]?.[key] || ""} onChange={e => { const value = e.target.value; if (locale === "en") change(key, value); else setTranslations(current => ({ ...current, [locale]: { ...(current[locale] || {}), [key]: value } })) }} /></div>
  const localizedArea = (label: string, key: string) => <div className="space-y-1.5 sm:col-span-2" key={key}><Label>{label}</Label><Textarea rows={5} value={locale === "en" ? form[key] || "" : translations?.[locale]?.[key] || ""} onChange={e => { const value = e.target.value; if (locale === "en") change(key, value); else setTranslations(current => ({ ...current, [locale]: { ...(current[locale] || {}), [key]: value } })) }} /></div>
  return <div>
    <div className="mb-4 flex flex-wrap items-center gap-3"><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="h-10 pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search events" /></div><Button onClick={add}><Plus className="mr-2 h-4 w-4" /> Add Event</Button></div>
    <Card><CardContent className="p-0">{loading ? <div className="flex justify-center py-14"><Loader2 className="h-6 w-6 animate-spin" /></div> : visible.length === 0 ? <div className="py-14 text-center text-sm text-muted-foreground"><CalendarDays className="mx-auto mb-2 h-8 w-8 opacity-40" />No events match this search.</div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-secondary/40 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Event</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border">{visible.map((event) => <tr key={event.id} className="hover:bg-secondary/30"><td className="px-4 py-3"><p className="font-medium">{event.title}</p><p className="text-xs text-muted-foreground">/{event.slug}</p></td><td className="px-4 py-3 text-xs text-muted-foreground">{new Date(event.startDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}</td><td className="px-4 py-3 text-xs text-muted-foreground">{event.location || event.venue || "—"}</td><td className="px-4 py-3"><Badge variant={event.status === "PUBLISHED" ? "default" : "secondary"}>{event.status}</Badge></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" aria-label={`Edit ${event.title}`} onClick={() => edit(event)}><Pencil className="h-4 w-4" /></Button>{event.status !== "ARCHIVED" && <Button size="icon" variant="ghost" aria-label={`Archive ${event.title}`} onClick={() => archive(event)}><Archive className="h-4 w-4" /></Button>}</div></td></tr>)}</tbody></table></div>}</CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{editing ? "Edit Event" : "Add Event"}</DialogTitle><DialogDescription>Draft events remain private. Publish confirmed event details for the public website.</DialogDescription></DialogHeader><div className="space-y-5 py-2">
      <section className="grid gap-4 rounded-lg border p-4 sm:grid-cols-2"><h3 className="text-sm font-semibold sm:col-span-2">Event and publication</h3>{field("Event title *", "title")}{field("URL slug *", "slug", "text", "annual-general-meeting")}<div className="space-y-1.5"><Label>Status</Label><Select value={form.status} onValueChange={(value) => change("status", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["DRAFT", "PUBLISHED", "ARCHIVED", "CANCELLED"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div>{field("Start date *", "startDate", "date")}{field("End date", "endDate", "date")}{field("Start time", "startTime", "time")}{field("End time", "endTime", "time")}</section>
      <section className="rounded-lg border p-4"><h3 className="mb-4 text-sm font-semibold">Event content and translations</h3><TranslationTabs active={locale} onChange={setLocale}>{() => <div className="grid gap-4 sm:grid-cols-2">{localizedInput("Category", "category")}{localizedArea("Description", "description")}{localizedInput("Venue", "venue")}{localizedInput("Location", "location")}{localizedInput("Organizer", "organizer")}</div>}</TranslationTabs></section>
      <section className="grid gap-4 rounded-lg border p-4 sm:grid-cols-2"><h3 className="text-sm font-semibold sm:col-span-2">Location, contact and image</h3>{field("Public contact", "contact")}<AdminImageUpload entity="event" value={form.image || ""} onChange={(url) => change("image", url)} label="Event image" />{field("Registration link", "registrationLink", "url", "https://")}</section>
    </div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{editing ? "Save changes" : "Save event"}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
