"use client"

import { useCallback, useEffect, useState } from "react"
import { Archive, Loader2, Pencil, Plus, Search, Users } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { TranslationTabs, getTrField, setTrField } from "@/components/admin/translation-tabs"
import { AdminImageUpload } from "@/components/admin/image-upload"
import { type Locale } from "@/lib/i18n"

type Leader = { id: string; name: string; position: string; category: string; regionId: string | null; department: string | null; level: string | null; photo: string | null; photoAlt: string | null; photoCredit: string | null; bio: string | null; email: string | null; phone: string | null; startDate: string | null; endDate: string | null; sortOrder: number; featured: boolean; status: string; translations: string }
type Region = { id: string; name: string }
const EMPTY = { name: "", position: "", category: "NATIONAL", regionId: "", department: "", level: "", photo: "", photoAlt: "", photoCredit: "", bio: "", email: "", phone: "", startDate: "", endDate: "", sortOrder: "0", featured: false, status: "INACTIVE" }
function parse(raw: string) { try { return JSON.parse(raw) } catch { return {} } }

export function LeadersManager({ role }: { role: string }) {
  const [leaders, setLeaders] = useState<Leader[]>([]); const [regions, setRegions] = useState<Region[]>([]); const [loading, setLoading] = useState(true)
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL"); const [editing, setEditing] = useState<Leader | null>(null); const [open, setOpen] = useState(false)
  const [saving, setSaving] = useState(false); const [form, setForm] = useState<any>(EMPTY); const [translations, setTranslations] = useState<Record<string, any>>({}); const [locale, setLocale] = useState<Locale>("en")
  const load = useCallback(async () => { setLoading(true); try { const res = await fetch("/api/admin/leaders"); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Could not load leadership records."); setLeaders(data.leaders || []); setRegions(data.regions || []) } catch (e) { toast.error(e instanceof Error ? e.message : "Could not load leaders.") } finally { setLoading(false) } }, [])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  function add() { setEditing(null); setForm({ ...EMPTY, category: role === "REGIONAL_EDITOR" ? "REGIONAL" : "NATIONAL", regionId: regions.length === 1 ? regions[0].id : "", status: "ACTIVE" }); setTranslations({}); setLocale("en"); setOpen(true) }
  function edit(leader: Leader) { setEditing(leader); setForm({ ...leader, regionId: leader.regionId || "", department: leader.department || "", level: leader.level || "", photo: leader.photo || "", photoAlt: leader.photoAlt || "", photoCredit: leader.photoCredit || "", bio: leader.bio || "", email: leader.email || "", phone: leader.phone || "", startDate: leader.startDate?.slice(0,10) || "", endDate: leader.endDate?.slice(0,10) || "", sortOrder: String(leader.sortOrder) }); setTranslations(parse(leader.translations)); setLocale("en"); setOpen(true) }
  function setBase(key: string, value: string) { setForm((current: any) => ({ ...current, [key]: value })) }
  async function save() {
    if (!form.name.trim() || !form.position.trim()) { toast.error("Enter the leader name and position."); return }
    setSaving(true)
    try {
      const payload = { ...form, regionId: form.regionId || null, sortOrder: Number(form.sortOrder) || 0, startDate: form.startDate || null, endDate: form.endDate || null, translations: JSON.stringify(translations) }
      const res = await fetch(editing ? `/api/admin/leaders/${editing.id}` : "/api/admin/leaders", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await res.json()
      if (!res.ok) throw new Error(data.error || "The leadership record could not be saved.")
      toast.success(editing ? "Leadership record updated." : "Leader added."); setOpen(false); await load()
    } catch (e) { toast.error(e instanceof Error ? e.message : "The leadership record could not be saved.") } finally { setSaving(false) }
  }
  async function archive(leader: Leader) { if (!confirm(`Archive ${leader.name}? This keeps the historical record but removes it from active leadership.`)) return; const res = await fetch(`/api/admin/leaders/${leader.id}`, { method: "DELETE" }); const data = await res.json().catch(() => ({})); if (!res.ok) { toast.error(data.error || "Could not archive leader."); return }; toast.success("Leader archived."); await load() }
  const visible = leaders.filter((leader) => (filter === "ALL" || leader.status === filter) && `${leader.name} ${leader.position} ${leader.department || ""}`.toLowerCase().includes(query.toLowerCase()))
  const input = (label: string, key: string, type = "text", placeholder = "") => <div className="space-y-1.5" key={key}><Label htmlFor={`leader-${key}`}>{label}</Label><Input id={`leader-${key}`} type={type} value={form[key] || ""} placeholder={placeholder} onChange={(e) => setBase(key, e.target.value)} /></div>
  return <div>
    <div className="mb-4 flex flex-wrap items-center gap-3"><div className="relative min-w-[200px] flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="h-10 pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search leaders" /></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="w-[160px]"><SelectValue /></SelectTrigger><SelectContent>{["ALL","ACTIVE","INACTIVE","ARCHIVED"].map((value) => <SelectItem key={value} value={value}>{value === "ALL" ? "All statuses" : value}</SelectItem>)}</SelectContent></Select><Button onClick={add}><Plus className="mr-2 h-4 w-4" /> Add Leader</Button></div>
    <Card><CardContent className="p-0">{loading ? <div className="flex justify-center py-14"><Loader2 className="h-6 w-6 animate-spin" /></div> : visible.length === 0 ? <div className="py-14 text-center text-sm text-muted-foreground"><Users className="mx-auto mb-2 h-8 w-8 opacity-40" />No leadership records match.</div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-secondary/40 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Name and position</th><th className="px-4 py-3">Level</th><th className="px-4 py-3">Region</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Order</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border">{visible.map((leader) => <tr key={leader.id} className="hover:bg-secondary/30"><td className="px-4 py-3"><p className="font-medium">{leader.name}</p><p className="text-xs text-muted-foreground">{leader.position}{leader.department ? ` · ${leader.department}` : ""}</p></td><td className="px-4 py-3"><Badge variant="outline">{leader.level || leader.category}</Badge></td><td className="px-4 py-3 text-xs text-muted-foreground">{regions.find((region) => region.id === leader.regionId)?.name || "—"}</td><td className="px-4 py-3"><Badge variant={leader.status === "ACTIVE" ? "default" : "secondary"}>{leader.status}</Badge></td><td className="px-4 py-3">{leader.sortOrder}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" onClick={() => edit(leader)} aria-label={`Edit ${leader.name}`}><Pencil className="h-4 w-4" /></Button>{leader.status !== "ARCHIVED" && <Button size="icon" variant="ghost" onClick={() => archive(leader)} aria-label={`Archive ${leader.name}`}><Archive className="h-4 w-4" /></Button>}</div></td></tr>)}</tbody></table></div>}</CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{editing ? "Edit Leader" : "Add Leader"}</DialogTitle><DialogDescription>Set an active status only when the role and identity are confirmed. Inactive and archived records are retained for history.</DialogDescription></DialogHeader>
      <div className="space-y-5 py-2"><section className="grid gap-4 rounded-lg border p-4 sm:grid-cols-2"><h3 className="text-sm font-semibold sm:col-span-2">Role and publication</h3>{input("Name (English) *", "name")}{input("Position (English) *", "position")}
        <div className="space-y-1.5"><Label>Level</Label><Select value={form.level || "NATIONAL"} onValueChange={(v) => setBase("level", v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["NATIONAL","REGIONAL","DEPARTMENT"].map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>
        <div className="space-y-1.5"><Label>Organization scope</Label><Select value={form.category} onValueChange={(v) => setBase("category", v)} disabled={role === "REGIONAL_EDITOR"}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{[["NATIONAL","National"],["REGIONAL","Regional"]].map(([v,l]) => <SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>
        {form.category === "REGIONAL" && <div className="space-y-1.5 sm:col-span-2"><Label>Region</Label><Select value={form.regionId} onValueChange={(v) => setBase("regionId", v)}><SelectTrigger><SelectValue placeholder="Select a region" /></SelectTrigger><SelectContent>{regions.map((region) => <SelectItem key={region.id} value={region.id}>{region.name}</SelectItem>)}</SelectContent></Select></div>}
        {input("Department", "department")}{input("Display order", "sortOrder", "number")}{input("Start date", "startDate", "date")}{input("End date", "endDate", "date")}
        <div className="space-y-1.5"><Label>Status</Label><Select value={form.status} onValueChange={(v) => setBase("status", v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["ACTIVE","INACTIVE","ARCHIVED"].map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>
        <div className="flex items-center gap-2 rounded-md border p-3"><Switch checked={!!form.featured} onCheckedChange={(v) => setForm((x: any) => ({ ...x, featured: v }))} id="leader-featured" /><Label htmlFor="leader-featured">Featured profile</Label></div></section>
        <section className="space-y-4 rounded-lg border p-4"><TranslationTabs active={locale} onChange={setLocale}>{(lang) => <div className="space-y-3" dir={lang === "ar" ? "rtl" : "ltr"}>{lang === "en" ? <><div className="space-y-1.5"><Label>Biography (English)</Label><Textarea rows={4} value={form.bio} onChange={(e) => setBase("bio", e.target.value)} /></div></> : <><div className="space-y-1.5"><Label>Name ({lang === "sw" ? "Kiswahili" : "العربية"})</Label><Input value={getTrField(translations, lang, "name")} onChange={(e) => setTranslations((v) => setTrField(v, lang, "name", e.target.value))} /></div><div className="space-y-1.5"><Label>Position ({lang === "sw" ? "Kiswahili" : "العربية"})</Label><Input value={getTrField(translations, lang, "position")} onChange={(e) => setTranslations((v) => setTrField(v, lang, "position", e.target.value))} /></div><div className="space-y-1.5"><Label>Biography ({lang === "sw" ? "Kiswahili" : "العربية"})</Label><Textarea rows={4} value={getTrField(translations, lang, "bio")} onChange={(e) => setTranslations((v) => setTrField(v, lang, "bio", e.target.value))} /></div></>}</div>}</TranslationTabs></section>
        <section className="grid gap-4 rounded-lg border p-4 sm:grid-cols-2"><h3 className="text-sm font-semibold sm:col-span-2">Contact and photograph</h3>{input("Public email", "email")}{input("Public phone", "phone")}<AdminImageUpload entity="leader" value={form.photo || ""} onChange={(url) => setBase("photo", url)} label="Leader portrait" />{input("Image alt text", "photoAlt")}{input("Image credit", "photoCredit")}</section>
      </div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{editing ? "Save changes" : "Save leader"}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
